name: matplotlive
channels:
    - conda-forge
dependencies:
    - matplotlib
    - pip >=21.3.1
    - pip:
        - furo >= 2023.8.17
        - sphinx >= 7.2.2
        - sphinx-autodoc-typehints
        - sphinx-favicon
        - sphinx-mdinclude
        - sphinx_rtd_theme
